config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :projects do
    resources :tasks
  end

  root "projects#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, :dependent => :destroy
  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  has_many :tasks_users
  has_many :users, through: :tasks_users, dependent: :delete_all
  belongs_to :project
  enum status: {New: 0, 'In progress': 1, Done: 2}
end

app/models/tasks_user.rb
class TasksUser < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks_users
  has_many :tasks, through: :tasks_users, dependent: :delete_all

  validates :first_name, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  layout :layout_by_controller

  protected

  def layout_by_controller
    devise_controller? ? 'devise' : 'application'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    if current_user.admin?
    @project = Project.new
    else
      redirect_to projects_url, alert: "You don't have permission"
      end
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    if current_user.admin?
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to projects_url, alert: "You don't have permission"
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if current_user.admin?
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
    else
      redirect_to projects_url, alert: "You don't have permission"
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    if current_user.admin?
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  else
    redirect_to projects_url, alert: "You don't have permission"
  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :summary, :start_date, :end_date)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :admin, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :admin, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project

  def new
    @task = @project.tasks.build
  end
  def create
    @task = @project.tasks.create(task_params)
    respond_to do |format|
    if @task.save
      format.html { redirect_to @project, notice: 'Task was successfully created.' }
      format.json { render :show, status: :created, location: @project.task }
    else
      format.html { render :new }
      format.json { render json: @task.errors, status: :unprocessable_entity }
    end
      end
  end

  def edit
    if current_user.admin?
    @task = Task.find(params[:id])
    else
      redirect_to @project, alert: "You don't have permission"
    end
  end

  def update
    if current_user.admin?
    @task = @project.tasks.find(params[:id])
    @task.update task_params
    redirect_to @project, notice: 'Task was successfully updated.'
    else
      redirect_to @project, alert: "You don't have permission"
    end
  end

  def destroy
    if current_user.admin?
    @task = @project.tasks.find(params[:id])
    if @task.destroy
      flash[:success] = "Task was deleted."
    else
      flash[:error] = "Task could not be deleted."
    end
    redirect_to @project, notice: 'Task was successfully deleted.'
    else
      redirect_to @project, alert: "You don't have permission"
    end
  end

  private
  def set_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params[:task].permit(:title, :description, :status, user_ids:[])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Projects manager</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background-color:rgba(163,200,202,0.58);">

<div class="container">

  <div class="row" style="text-align: right; background-color: rgba(139,167,212,0.57)">
    <div class="col-lg-12 col-md-12 col-sm-12">
      Logged in as <strong><%= current_user.first_name %> <%= current_user.last_name %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
    </div>
  </div>

  <div class="row center" style="margin-bottom:15px; border-bottom-left-radius: 80px; border-bottom-right-radius: 80px; background-color: rgba(139,167,212,0.57)">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <h1>Projects manager</h1>
    </div>
  </div>

  <div class="row center">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>

  <%= yield %>

</div>
</body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Program</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="background-color:rgba(163,200,202,0.58);">
<div class="container">

  <div class="row">
    <div class="col-lg-4 col-md-4 col-sm-10"></div>
    <div class="col-lg-4 col-md-4 col-sm-10">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>


  <%= yield %>

    </div>
  </div>
</div>
</body>

</html>

app/views/projects/_form.html.erb
<div class="row">
  <div class="col-lg-4"></div>

  <%= simple_form_for(@project) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation" class="col-lg-4">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="col-lg-4"></div>
    </div>

    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4">
        <div class="field">
          <%= form.input :name, id: :project_name %>
        </div>

        <div class="field">
          <%= form.input :summary, id: :project_summary %>
        </div>
        <div class="row">
          <div class="col-lg-6">
            <%= form.input :start_date, as: :date, html5: true %>
          </div>
          <div class="col-lg-6">
            <%= form.input :end_date, as: :date, html5: true %>
          </div>
        </div>


        <div class="actions">
          <%= form.button :submit, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  <% end %>

app/views/projects/edit.html.erb
<div class="row">
  <div class="col-lg-12" style="text-align:center">
    <h1>Editing project</h1>
  </div>
</div>

<%= render 'form', project: @project %>

<div class="row" style="text-align:right">
  <%= link_to 'Back', @project, :class => "btn btn-warning" %>
</div>

app/views/projects/index.html.erb
<div class="row center bottom">
  <div class="col-lg-12 col-md-12 col-sm-12">
    <h2>List of projects</h2>
  </div>
</div>

<table class="table table-hover">
  <thead>
  <tr>
    <th>Name</th>
    <th>Summary</th>
    <th>Start date</th>
    <th>End date</th>
    <th class="center" colspan="2">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.summary %></td>
      <td><%= project.start_date %></td>
      <td><%= project.end_date %></td>
      <td><%= link_to 'Show', project %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<div class="row center">
  <%= link_to 'New project', new_project_path, :class => "btn btn-primary" %>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-lg-12" style="text-align:center">
    <h1>New project</h1>
  </div>
</div>

<%= render 'form', project: @project %>

<div class="row" style="text-align:right">
  <%= link_to 'Back', projects_path, :class => "btn btn-warning" %>
</div>

app/views/projects/new.js.erb
$('#modal').integrateDatepicker();

app/views/projects/show.html.erb
<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 center">
    <h2><%= @project.name %></h2>
  </div>
</div>
<div class="row">
  <p>
    <strong>Summary:</strong>
    <%= @project.summary %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= @project.start_date %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= @project.end_date %>
  </p>
  <%= link_to 'Edit', edit_project_path(@project), :class => "btn btn-info" %>
</div>

<div class="row">
  <div class="col-lg-12 col-md-12 col-sm-12 center">
    <h3>Tasks</h3>
  </div>

  <table class="table table-hover">
    <thead>
    <tr>
      <th>Title</th>
      <th>Desription</th>
      <th>Status</th>
      <th>Users</th>
      <th class="center" colspan="2">Actions</th>
    </tr>
    </thead>
    <%= render @project.tasks %>
  </table>
  <div class="col-lg-12 center">
    <h2> <%= link_to 'Add Task', new_project_task_path(@project), :class => "btn btn-primary" %> </h2>
  </div>
</div>

<div class="row" style="text-align:right">
  <%= link_to 'Back', projects_path, :class => "btn btn-warning" %>
</div>

app/views/tasks/_form.html.erb
<div class="row">
  <div class="col-lg-4"></div>
  <% if task.errors.any? %>
    <div id="error_explanation" class="col-lg-4">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-lg-4"></div>
</div>
<div class="row center">
  <div class="col-lg-4"></div>
  <div class="col-lg-4">
    <%= simple_form_for([@project, @task]) do |f| %>

      <%= f.input :title, required: true %>
      <%= f.input :description %>
      <%= f.input :status, :collection => Task.statuses.map {|a| [a.first, a.first]}, :include_blank => false %>
      <h4>Users</h4>
      <div class="row">
        <%= f.collection_check_boxes(:user_ids, User.all, :id, :first_name) do |b| %>
          <div class="col-lg-4"> <%= b.label {b.check_box + b.object.first_name + " " + b.object.last_name} %></div>
        <% end %>
      </div>
      <br>
      <%= f.button :submit, "Submit", class: 'btn btn-primary' %>
    <% end %>

  </div>
  <div class="col-lg-4"></div>
</div>

app/views/tasks/_task.html.erb
<tr>
  <td><%= task.title %></td>
  <td><%= task.description %></td>
  <td><%= task.status %></td>
  <td>
    <% @users = task.users %>
    <% @users.each do |user| %>
      <%= user.first_name %>
      <%= user.last_name %><br/>
    <% end %>
  </td>
  <td>
    <%= link_to "Edit", edit_project_task_path(@project.id, task.id) %>
  </td>
  <td>
    <%= link_to "Delete", project_task_path(@project, task.id),
                method: :delete, data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-lg-12 center bottom">
    <h2>Editing task</h2>
  </div>
</div>

<%= render 'form', task: @task %>

<div class="row" style="text-align:right">
  <%= link_to 'Back', @project, :class => "btn btn-warning" %>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-lg-12 center bottom">
    <h2>New task</h2>
  </div>
</div>
<%= render 'form', task: @task %>

<div class="row" style="text-align:right">
  <%= link_to 'Back', @project, :class => "btn btn-warning" %>
</div>